name: 'register-eb-lambda-action'
description: 'register Lambda function listening to ECS events and EventBridge to connect lambda functions and ecs clusters'
inputs:
  name:
    description: 'The name of the event rule'
    required: true
  description:
    description: 'The description of the event rule'
    required: true
  region:
    description: 'AWS region. The region of AWS ECS should be same as the one of AWS EventBridge.'
    required: true
  lambda-function-name:
    description: 'The name of listener lambda function. This action assume that lambda function is already created.'
    required: true
  event-bus:
    description: 'The event bus which this rule will be set. Default is "default"'
    required: false
  clusters:
    description: "The names of the ECS service's cluster(optional). If you want to specify targeted clusters, give ARNs of cluster as multi-line input. Default is all clusters."
    required: false
  event-type: # 'STATE_CHANGE' | 'CLOUDTRAIL_API_CALL'
    description: 'The types of the event(optional). Default is listening to every events'
    required: false
  detail-event-type: # "ECS Task State Change" | "ECS Container Instance State Change" | "ECS Deployment State Change"
    description: 'The detailed types of event(optional). This input should be used with STATE_CHANGE event type. If you want to specify detailed event types, give it as multi-line input. Default is all detailed-events.'
    required: false
  event-name:
    description: 'The event name of API Call through CloudTrail(optional). More info: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-aws-service-specific-topics.html'
    required: false
  
outputs:
  rule:
    description: 'The arn of created rule'

runs:
  using: 'node16'
  main: 'dist/index.js'