name: 'register-eb-lambda-action'
description: 'register Lambda function listening to ECS events and EventBridge to connect lambda functions and ecs clusters'
inputs:
  name:
    description: 'The name of the event rule'
    required: true
  description:
    description: 'The description of the event rule'
    required: true
  region:
    description: 'AWS region. The region of AWS ECS should be same as the one of AWS EventBridge.'
    required: true
  event-bus:
    description: 'The event bus which this rule will be set. Default is "default"'
    required: false
  clusters:
    description: "The names of the ECS service's cluster(optional). If you want to specify targeted clusters, give ARNs of cluster as array. Default is all clusters."
    required: false
  event-type:
    description: 'The types of the event(optional). If you want to bridge only selected events, give types of event as array. Default is all events'
    required: false
  detail-event-type:
    description: 'The detailed types of event(optional).'
    required: false
  event-name:
    description: 'The event name of API Call through CloudTrail(optional).'
    required: false

outputs:
  rule:
    description: 'The arn of created rule'

runs:
  using: 'node16'
  main: 'dist/index.js'